# Generated by Django 6.0.6 on 2026-06-09 18:20

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '0001_initial'),
        ('payments', '0002_payment_merchant_alter_payment_commission_rate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('full_name', models.CharField(blank=True, max_length=120)),
                ('country_code', models.CharField(blank=True, help_text='ISO 3166-1 alpha-2', max_length=2)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('affiliate_code', models.CharField(blank=True, db_index=True, max_length=50)),
                ('referrer_url', models.URLField(blank=True)),
                ('discount_code_used', models.CharField(blank=True, max_length=50)),
                ('discount_amount_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('selected_tier_index', models.PositiveSmallIntegerField(blank=True, help_text='Index of chosen tier (for TIERED pricing).', null=True)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('pending_email_verif', 'Awaiting Email Verification'), ('payment_created', 'Payment Session Created'), ('granted', 'Access Granted'), ('abandoned', 'Abandoned'), ('refunded', 'Refunded'), ('revoked', 'Revoked by Admin'), ('expired', 'Access Expired')], db_index=True, default='initiated', max_length=30)),
                ('access_expires_at', models.DateTimeField(blank=True, null=True)),
                ('unlock_delivered', models.BooleanField(default=False)),
                ('unlock_delivered_at', models.DateTimeField(blank=True, null=True)),
                ('unlock_error', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_grant', to='payments.payment')),
            ],
            options={
                'verbose_name': 'Access Grant',
                'verbose_name_plural': 'Access Grants',
                'db_table': 'access_grants',
            },
        ),
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, default=uuid.uuid4, help_text='The secret token sent to buyer. Can be UUID or signed string.', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this token expires. Null = never.', null=True)),
                ('use_count', models.PositiveIntegerField(default=0)),
                ('max_uses', models.PositiveIntegerField(default=1, help_text='0 = unlimited.')),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('grant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access_token', to='gating.accessgrant')),
            ],
            options={
                'verbose_name': 'Access Token',
                'verbose_name_plural': 'Access Tokens',
                'db_table': 'access_tokens',
            },
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('view_checkout', 'View Checkout Page'), ('submit_checkout', 'Submit Checkout Form'), ('payment_redirect', 'Redirect to PayRam'), ('payment_return', 'Return from PayRam'), ('token_verification', 'Token Verification Attempt'), ('unlock_delivery', 'Unlock Delivered'), ('unlock_failed', 'Unlock Failed')], max_length=50)),
                ('success', models.BooleanField(default=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('request_headers', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='gating.accessgrant')),
                ('token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='gating.accesstoken')),
            ],
            options={
                'db_table': 'access_logs',
            },
        ),
        migrations.CreateModel(
            name='EmbedToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embed_tokens', to='gating.accessgrant')),
            ],
            options={
                'db_table': 'embed_tokens',
            },
        ),
        migrations.CreateModel(
            name='GatedAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='Public URL: /gating/<slug>/', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Markdown supported. Shown before payment.')),
                ('thumbnail_url', models.URLField(blank=True, help_text='Thumbnail / cover image displayed on checkout.')),
                ('video_preview_url', models.URLField(blank=True, help_text='Optional preview video (e.g., YouTube/Vimeo).')),
                ('asset_type', models.CharField(choices=[('url', 'External URL'), ('telegram', 'Telegram Group'), ('discord', 'Discord Server Role'), ('file', 'File Download (hosted on CashSpace or external)'), ('api_key', 'API Key / Password'), ('embed', 'Embed Code (iframe / script)'), ('webhook', "Custom Webhook (POST to buyer's endpoint)"), ('content', 'Hidden Text / HTML Content')], default='url', max_length=20)),
                ('unlock_value', models.TextField(blank=True, help_text='The locked resource. For URL/Telegram: the link. For API_KEY/CONTENT: the secret. For FILE: path or external URL. For EMBED: HTML/JS snippet. For WEBHOOK: endpoint URL.')),
                ('unlock_config', models.JSONField(blank=True, default=dict, help_text='Extra configuration:\n  - Discord: {guild_id, role_id, bot_token, message}\n  - URL: {redirect_delay_seconds, add_token_as_query_param (bool)}\n  - WEBHOOK: {headers, method, retry_count}\n  - EMBED: {width, height, sandbox}\n  - FILE: {expiry_seconds, download_limit}\n  - API_KEY: {instructions, regenerate_on_each_grant}')),
                ('pricing_type', models.CharField(choices=[('fixed', 'Fixed Price'), ('donation', 'Pay What You Want'), ('subscription', 'Recurring Subscription'), ('tiered', 'Multi‑Tier (different prices / durations)')], default='fixed', max_length=20)),
                ('price_usd', models.DecimalField(blank=True, decimal_places=2, help_text='Fixed price in USD. Null for DONATION / TIERED.', max_digits=12, null=True)),
                ('min_price_usd', models.DecimalField(decimal_places=2, default=5, help_text='Minimum allowed for DONATION type.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('max_price_usd', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum allowed for DONATION type. Null = no max.', max_digits=12, null=True)),
                ('price_tiers', models.JSONField(blank=True, default=list, help_text='List of tiers: [{"price": 9.99, "duration_value": 30, "duration_unit": "days", "description": "Standard"}, ...]')),
                ('subscription_interval_value', models.PositiveIntegerField(default=30, help_text='How many units between recurring charges.')),
                ('subscription_interval_unit', models.CharField(choices=[('hours', 'Hours'), ('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months'), ('years', 'Years')], default='days', help_text='Unit for subscription interval (days, weeks, months).', max_length=10)),
                ('subscription_trial_days', models.PositiveIntegerField(default=0, help_text='Free trial days before first charge.')),
                ('subscription_max_cycles', models.PositiveIntegerField(blank=True, help_text='Max number of payments. Null = indefinite until cancelled.', null=True)),
                ('grant_duration_value', models.PositiveIntegerField(default=0, help_text='How long access lasts. 0 = permanent.')),
                ('grant_duration_unit', models.CharField(blank=True, choices=[('hours', 'Hours'), ('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months'), ('years', 'Years')], help_text='Unit for grant duration.', max_length=10)),
                ('settlement_blockchain', models.CharField(default='TRX', help_text='Blockchain for payout (BTC, ETH, TRX, BASE, POL).', max_length=10)),
                ('settlement_currency', models.CharField(default='USDT', help_text='Currency/token for payout.', max_length=10)),
                ('settlement_wallet_address', models.CharField(blank=True, help_text="Explicit wallet. Falls back to owner's default.", max_length=100)),
                ('token_expires_after_grant_value', models.PositiveIntegerField(default=0, help_text='Hours after grant until token expires (0 = never).')),
                ('token_max_uses', models.PositiveIntegerField(default=1, help_text='How many times the token can be used. 1 = single‑use.')),
                ('token_requires_email_verification', models.BooleanField(default=False, help_text='If True, buyer must click a link in email before token is activated.')),
                ('is_active', models.BooleanField(default=True)),
                ('max_grants', models.PositiveIntegerField(blank=True, help_text='Total number of sales allowed. Null = unlimited.', null=True)),
                ('max_grants_per_email', models.PositiveIntegerField(default=1, help_text='How many times the same email can buy this asset. 0 = unlimited.')),
                ('allowed_countries', models.JSONField(blank=True, default=list, help_text='ISO country codes allowed (empty = all). Ex: ["US", "GB"]')),
                ('blocked_countries', models.JSONField(blank=True, default=list, help_text='ISO country codes blocked (overrides allowed).')),
                ('require_captcha', models.BooleanField(default=False, help_text='Require CAPTCHA on checkout form (anti‑bot).')),
                ('allowed_referrers', models.JSONField(blank=True, default=list, help_text="List of allowed referrer domains (e.g., ['example.com']). Empty = all.")),
                ('discount_codes', models.JSONField(blank=True, default=dict, help_text='Discount codes: {"SAVE10": {"type": "percent", "value": 10, "max_uses": 100, "expires_at": "2026-12-31"}}')),
                ('affiliate_commission_percent', models.DecimalField(decimal_places=2, default=0, help_text='Percentage of sale given to affiliate who referred buyer.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('affiliate_cookie_days', models.PositiveIntegerField(default=30, help_text='Days affiliate cookie lasts.')),
                ('dynamic_pricing_enabled', models.BooleanField(default=False)),
                ('base_price_usd', models.DecimalField(blank=True, decimal_places=2, help_text='Base price before dynamic multiplier.', max_digits=12, null=True)),
                ('price_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Multiplier applied to base price based on demand.', max_digits=5)),
                ('demand_window_days', models.PositiveIntegerField(default=7, help_text='Days to look back for sales velocity.')),
                ('steps', models.JSONField(blank=True, default=list, help_text='For content that unlocks gradually: [{"step": 1, "delay_days": 0, "value": "first video URL"}, ...]. Only applies to asset_type=CONTENT/URL.')),
                ('success_message', models.TextField(blank=True, help_text='Custom message shown on success page / email.')),
                ('success_redirect_url', models.URLField(blank=True, help_text='Redirect buyer here after payment (overrides token delivery).')),
                ('send_welcome_email', models.BooleanField(default=True)),
                ('welcome_email_template', models.TextField(blank=True, help_text='Custom email body with placeholders: {buyer_name}, {asset_title}, {access_link}.')),
                ('webhook_url', models.URLField(blank=True, help_text='POST to this URL on every successful grant (with access token).')),
                ('webhook_secret', models.CharField(blank=True, help_text='HMAC secret to sign webhook payloads.', max_length=200)),
                ('nft_gate_contract', models.CharField(blank=True, help_text='Optional: NFT contract address required to access (buyer must own NFT).', max_length=100)),
                ('nft_gate_min_balance', models.PositiveIntegerField(blank=True, help_text='Minimum number of NFTs required.', null=True)),
                ('blockchain_network', models.CharField(blank=True, help_text="e.g., 'ethereum', 'polygon' for NFT gating.", max_length=20)),
                ('bundled_assets', models.ManyToManyField(blank=True, help_text='Other assets included when this asset is purchased.', related_name='bundled_in', to='gating.gatedasset')),
                ('merchant', models.ForeignKey(blank=True, help_text='Optional: link to a merchant account for advanced dashboard', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gated_assets', to='merchants.merchant')),
                ('owner', models.ForeignKey(help_text='Creator who owns this asset', on_delete=django.db.models.deletion.CASCADE, related_name='gated_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gated Asset',
                'verbose_name_plural': 'Gated Assets',
                'db_table': 'gated_assets',
            },
        ),
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('percent', 'Percentage off'), ('fixed', 'Fixed amount off')], default='percent', max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Percent (0-100) or fixed USD', max_digits=10)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('max_uses', models.PositiveIntegerField(default=1)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('min_purchase_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('assets', models.ManyToManyField(blank=True, help_text='Leave empty = apply to all', related_name='discounts', to='gating.gatedasset')),
            ],
            options={
                'db_table': 'discount_codes',
            },
        ),
        migrations.CreateModel(
            name='AffiliateClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliate_code', models.CharField(db_index=True, max_length=50)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('referrer_url', models.URLField(blank=True)),
                ('converted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gating.accessgrant')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gating.gatedasset')),
            ],
            options={
                'db_table': 'affiliate_clicks',
            },
        ),
        migrations.AddField(
            model_name='accessgrant',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_grants', to='gating.gatedasset'),
        ),
        migrations.AddIndex(
            model_name='accesstoken',
            index=models.Index(fields=['token'], name='access_toke_token_da8eb7_idx'),
        ),
        migrations.AddIndex(
            model_name='accesstoken',
            index=models.Index(fields=['expires_at'], name='access_toke_expires_c63347_idx'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['grant', 'created_at'], name='access_logs_grant_i_e9cf89_idx'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['action', 'created_at'], name='access_logs_action_86b25a_idx'),
        ),
        migrations.AddIndex(
            model_name='gatedasset',
            index=models.Index(fields=['slug'], name='gated_asset_slug_cb401b_idx'),
        ),
        migrations.AddIndex(
            model_name='gatedasset',
            index=models.Index(fields=['owner', 'is_active'], name='gated_asset_owner_i_6e1699_idx'),
        ),
        migrations.AddIndex(
            model_name='gatedasset',
            index=models.Index(fields=['pricing_type', 'price_usd'], name='gated_asset_pricing_d4ee32_idx'),
        ),
        migrations.AddIndex(
            model_name='affiliateclick',
            index=models.Index(fields=['affiliate_code', 'created_at'], name='affiliate_c_affilia_773ff5_idx'),
        ),
        migrations.AddIndex(
            model_name='accessgrant',
            index=models.Index(fields=['asset', 'status'], name='access_gran_asset_i_a14a1d_idx'),
        ),
        migrations.AddIndex(
            model_name='accessgrant',
            index=models.Index(fields=['email', 'asset'], name='access_gran_email_b5fc37_idx'),
        ),
        migrations.AddIndex(
            model_name='accessgrant',
            index=models.Index(fields=['affiliate_code'], name='access_gran_affilia_61e5a4_idx'),
        ),
        migrations.AddIndex(
            model_name='accessgrant',
            index=models.Index(fields=['created_at'], name='access_gran_created_038816_idx'),
        ),
    ]
