# Generated by Django 6.0.6 on 2026-06-08 15:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('PAYMENT_SUCCESS', 'Payment Succeeded'), ('PAYOUT_COMPLETED', 'Payout Completed'), ('PAYOUT_FAILED', 'Payout Failed'), ('WALLET_ADDED', 'Wallet Added'), ('WALLET_UPDATED', 'Wallet Updated'), ('WALLET_DELETED', 'Wallet Deleted'), ('VERIFICATION_REMINDER', 'Verification Reminder'), ('ADMIN_BROADCAST', 'Admin Broadcast')], db_index=True, max_length=50)),
                ('level', models.CharField(choices=[('success', 'Success'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='notificatio_user_id_611c58_idx'), models.Index(fields=['user', 'is_read'], name='notificatio_user_id_a4dd5c_idx'), models.Index(fields=['type', 'created_at'], name='notificatio_type_cb6908_idx'), models.Index(fields=['level'], name='notificatio_level_469423_idx')],
            },
        ),
    ]
