# Generated by Django 6.0.6 on 2026-06-08 14:47

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_usd', models.DecimalField(decimal_places=2, help_text='Full amount the user is charged in USD (card or crypto checkout)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('blockchain_code', models.CharField(choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('TRX', 'Tron'), ('BASE', 'Base'), ('POL', 'Polygon')], help_text='Blockchain to send payout on (BTC, ETH, TRX, BASE, POL)', max_length=10)),
                ('currency_code', models.CharField(choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('USDT', 'Tether USD'), ('USDC', 'USD Coin'), ('TRX', 'Tron')], help_text='Currency/token to send (BTC, ETH, USDT, USDC, TRX)', max_length=10)),
                ('destination_wallet', models.CharField(help_text="User's wallet address for the selected blockchain/token", max_length=100)),
                ('exchange_rate_usd_to_crypto', models.DecimalField(blank=True, decimal_places=8, help_text='Rate used: 1 USD = X crypto (e.g., 1.00 for USDC, 0.000027 for BTC)', max_digits=20, null=True)),
                ('payout_crypto_amount', models.DecimalField(blank=True, decimal_places=8, help_text='Amount in crypto sent to user (payout_usd × exchange_rate)', max_digits=20, null=True)),
                ('payout_usd_equivalent', models.DecimalField(blank=True, decimal_places=2, help_text='USD equivalent of payout_crypto_amount (for commission calculation)', max_digits=12, null=True)),
                ('commission_rate', models.DecimalField(decimal_places=4, default=Decimal('0.30'), help_text='Commission rate applied (e.g., 0.3000 = 30%%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('commission_usd', models.DecimalField(blank=True, decimal_places=2, help_text='Commission amount kept by CashSpace (amount_usd × commission_rate)', max_digits=12, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('CARD', 'Card (Visa/Mastercard via onramp)'), ('CRYPTO_USDC', 'Crypto - USDC'), ('CRYPTO_USDT', 'Crypto - USDT'), ('CRYPTO_BTC', 'Crypto - BTC'), ('CRYPTO_ETH', 'Crypto - ETH')], help_text='Payment method the customer used on PayRam checkout', max_length=20, null=True)),
                ('payment_method_details', models.JSONField(blank=True, default=dict, help_text='Additional payment method metadata (card brand, last4, etc.)')),
                ('payram_reference_id', models.CharField(blank=True, db_index=True, help_text='PayRam reference_id returned when creating payment session', max_length=200)),
                ('payram_payment_url', models.URLField(blank=True, help_text='PayRam-hosted checkout URL — redirect user here', max_length=500)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('OPEN', 'Open'), ('FILLED', 'Completed'), ('PARTIALLY_FILLED', 'Partially Filled'), ('OVER_FILLED', 'Over-Filled'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed')], db_index=True, default='PENDING', help_text='Current status of the payment on PayRam', max_length=20)),
                ('payram_raw_status', models.CharField(blank=True, help_text='Raw paymentState string received from PayRam', max_length=30)),
                ('payram_payout_id', models.IntegerField(blank=True, db_index=True, help_text='PayRam payout ID from POST /api/v1/withdrawal/merchant', null=True)),
                ('payout_status', models.CharField(choices=[('NOT_INITIATED', 'Not Initiated'), ('pending-approval', 'Pending Approval'), ('approved', 'Approved'), ('completed', 'Completed'), ('failed', 'Failed')], default='NOT_INITIATED', help_text="Current status of the outgoing payout to the user's wallet", max_length=30)),
                ('payout_initiated_at', models.DateTimeField(blank=True, help_text='Timestamp when create_payout() was called', null=True)),
                ('payout_completed_at', models.DateTimeField(blank=True, help_text="Timestamp when payout reached 'completed' status", null=True)),
                ('payout_error', models.TextField(blank=True, help_text='Error detail if payout failed')),
                ('last_webhook_at', models.DateTimeField(blank=True, help_text='Last time we received a webhook for this payment', null=True)),
                ('webhook_count', models.PositiveIntegerField(default=0, help_text='Number of webhooks received for this payment')),
                ('error_message', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(help_text='User who initiated this payment', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserCryptoWallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('blockchain_code', models.CharField(choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('TRX', 'Tron'), ('BASE', 'Base'), ('POL', 'Polygon')], help_text='Blockchain this wallet belongs to', max_length=10)),
                ('currency_code', models.CharField(choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('USDT', 'Tether USD'), ('USDC', 'USD Coin'), ('TRX', 'Tron')], help_text='Currency/token this wallet receives', max_length=10)),
                ('wallet_address', models.CharField(help_text="User's wallet address (validate based on blockchain_code)", max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this wallet can receive payouts')),
                ('is_default', models.BooleanField(default=False, help_text='If true, this is the preferred wallet for this blockchain+currency')),
                ('label', models.CharField(blank=True, help_text="User-friendly name (e.g., 'My TRX USDT wallet')", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who owns this wallet address', on_delete=django.db.models.deletion.CASCADE, related_name='crypto_wallets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Crypto Wallet',
                'verbose_name_plural': 'User Crypto Wallets',
                'db_table': 'user_crypto_wallets',
                'ordering': ['user', 'blockchain_code', 'currency_code'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payram_reference_id', models.CharField(blank=True, db_index=True, help_text='PayRam reference_id from the webhook', max_length=200)),
                ('event_type', models.CharField(blank=True, help_text='Event type: OPEN, FILLED, PARTIALLY_FILLED, OVER_FILLED, CANCELLED', max_length=100)),
                ('payload', models.JSONField(default=dict, help_text='Complete raw webhook payload from PayRam')),
                ('signature_valid', models.BooleanField(default=False, help_text='Whether the API-Key header matched our secret')),
                ('processed', models.BooleanField(default=False, help_text='Whether this event was successfully processed')),
                ('error', models.TextField(blank=True, help_text='Processing error if any')),
                ('payment', models.ForeignKey(blank=True, help_text='Related payment if successfully matched', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='payments.payment')),
            ],
            options={
                'verbose_name': 'Webhook Event',
                'verbose_name_plural': 'Webhook Events',
                'db_table': 'webhook_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', 'status'], name='payments_user_id_1b771c_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payram_reference_id'], name='payments_payram__067284_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payram_payout_id'], name='payments_payram__b2ac37_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payout_status'], name='payments_payout__bd731d_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['blockchain_code', 'currency_code'], name='payments_blockch_7fd506_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'payout_status'], name='payments_status_1587ce_idx'),
        ),
        migrations.AddConstraint(
            model_name='usercryptowallet',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user', 'blockchain_code', 'currency_code'), name='unique_default_per_user_per_chain_token'),
        ),
        migrations.AlterUniqueTogether(
            name='usercryptowallet',
            unique_together={('user', 'blockchain_code', 'currency_code', 'is_default'), ('user', 'blockchain_code', 'currency_code', 'wallet_address')},
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['payram_reference_id', 'event_type'], name='webhook_eve_payram__d8273f_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['processed', 'created_at'], name='webhook_eve_process_8c85e6_idx'),
        ),
    ]
