# Generated by Django 6.0.6 on 2026-06-09 10:25

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0001_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='merchant',
            field=models.ForeignKey(blank=True, help_text='Merchant whose product is being purchased. Null for direct purchases.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='merchants.merchant'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='commission_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.30'), help_text='Commission rate applied (e.g., 0.3000 = 30%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='destination_wallet',
            field=models.CharField(help_text='Wallet address receiving the payout (buyer wallet or merchant settlement wallet)', max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payout_crypto_amount',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Amount in crypto sent to recipient (payout_usd × exchange_rate)', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payout_status',
            field=models.CharField(choices=[('NOT_INITIATED', 'Not Initiated'), ('pending-approval', 'Pending Approval'), ('approved', 'Approved'), ('completed', 'Completed'), ('failed', 'Failed')], default='NOT_INITIATED', help_text='Current status of the outgoing payout to the recipient wallet', max_length=30),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payout_usd_equivalent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='USD equivalent of payout after commission deduction', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(help_text='User who initiated this payment (buyer account, or anonymous guest via merchant checkout)', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['merchant', 'status'], name='payments_merchan_ad6aef_idx'),
        ),
    ]
