# Generated by Django 6.0.6 on 2026-06-09 18:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('bio', models.TextField(blank=True, help_text='Public bio shown on your creator page')),
                ('avatar_url', models.URLField(blank=True)),
                ('cover_image_url', models.URLField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('twitter_handle', models.CharField(blank=True, max_length=50)),
                ('telegram_handle', models.CharField(blank=True, max_length=50)),
                ('custom_payout_wallet', models.CharField(blank=True, max_length=100)),
                ('custom_payout_blockchain', models.CharField(blank=True, default='TRX', max_length=10)),
                ('custom_payout_currency', models.CharField(blank=True, default='USDT', max_length=10)),
                ('commission_rate_override', models.DecimalField(blank=True, decimal_places=4, help_text='Override global commission for this creator. Null = use global.', max_digits=5, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_docs', models.JSONField(blank=True, default=list)),
                ('max_assets', models.PositiveIntegerField(default=100)),
                ('max_monthly_sales', models.PositiveIntegerField(default=1000)),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('total_sales', models.PositiveIntegerField(default=0)),
                ('total_revenue_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='creator_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'creator_profiles',
            },
        ),
        migrations.CreateModel(
            name='PayableAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True, help_text='Markdown supported')),
                ('thumbnail_url', models.URLField(blank=True)),
                ('video_preview_url', models.URLField(blank=True, help_text='YouTube/Vimeo preview')),
                ('asset_type', models.CharField(choices=[('url', 'External URL (course, video, private page)'), ('file', 'File Download (PDF, ZIP, MP4)'), ('content', 'Hidden Text / HTML'), ('api_key', 'API Key / License Key'), ('telegram', 'Telegram Group Invite'), ('discord', 'Discord Role Grant'), ('embed', 'Embeddable Widget (iframe/script)')], default='url', max_length=20)),
                ('unlock_value', models.TextField(help_text='The URL, file path, secret, or invite link')),
                ('unlock_config', models.JSONField(blank=True, default=dict, help_text='\n        Extra config for advanced types:\n        - discord: {"guild_id": "...", "role_id": "...", "bot_token": "..."}\n        - url: {"redirect_delay": 0, "add_token": true}\n        - file: {"expiry_seconds": 3600, "max_downloads": 3}\n        - embed: {"width": 800, "height": 600}\n    ')),
                ('pricing_type', models.CharField(choices=[('fixed', 'Fixed Price'), ('pwyw', 'Pay What You Want'), ('subscription', 'Recurring Subscription'), ('tiered', 'Multi‑Tier Pricing')], default='fixed', max_length=20)),
                ('price_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('min_price_usd', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=12)),
                ('max_price_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_tiers', models.JSONField(blank=True, default=list)),
                ('subscription_interval_days', models.PositiveIntegerField(default=30, help_text='Billing interval in days')),
                ('subscription_trial_days', models.PositiveIntegerField(default=0)),
                ('subscription_max_cycles', models.PositiveIntegerField(default=0, help_text='0 = indefinite')),
                ('access_duration_value', models.PositiveIntegerField(default=0)),
                ('access_duration_unit', models.CharField(choices=[('permanent', 'Permanent'), ('hours', 'Hours'), ('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months'), ('years', 'Years')], default='permanent', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('max_sales', models.PositiveIntegerField(blank=True, help_text='Max total sales (null = unlimited)', null=True)),
                ('max_sales_per_buyer', models.PositiveIntegerField(default=1, help_text='Per email address')),
                ('allowed_countries', models.JSONField(blank=True, default=list, help_text='ISO codes, empty = all')),
                ('require_captcha', models.BooleanField(default=False)),
                ('custom_settlement_wallet', models.CharField(blank=True, max_length=100)),
                ('custom_settlement_blockchain', models.CharField(blank=True, default='TRX', max_length=10)),
                ('custom_settlement_currency', models.CharField(blank=True, default='USDT', max_length=10)),
                ('token_expires_hours', models.PositiveIntegerField(default=0, help_text='0 = never')),
                ('token_max_uses', models.PositiveIntegerField(default=1, help_text='1 = single use')),
                ('success_message', models.TextField(blank=True)),
                ('success_redirect_url', models.URLField(blank=True)),
                ('send_welcome_email', models.BooleanField(default=True)),
                ('custom_email_template', models.TextField(blank=True)),
                ('webhook_url', models.URLField(blank=True)),
                ('webhook_secret', models.CharField(blank=True, max_length=200)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('conversion_count', models.PositiveIntegerField(default=0)),
                ('revenue_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='creator.creatorprofile')),
            ],
            options={
                'db_table': 'payable_assets',
            },
        ),
        migrations.CreateModel(
            name='CreatorSale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer_email', models.EmailField(max_length=254)),
                ('buyer_name', models.CharField(blank=True, max_length=120)),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commission_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('net_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('processing', 'Processing'), ('completed', 'Completed (paid to creator)'), ('refunded', 'Refunded'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('access_token', models.CharField(blank=True, max_length=255)),
                ('access_grant_id', models.UUIDField(blank=True, help_text='Reference to gating.AccessGrant', null=True)),
                ('payment_id', models.UUIDField(blank=True, help_text='Reference to payments.Payment', null=True)),
                ('payout_id', models.CharField(blank=True, help_text='PayRam payout ID', max_length=100)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='creator.payableasset')),
            ],
            options={
                'db_table': 'creator_sales',
            },
        ),
        migrations.CreateModel(
            name='CreatorDiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50)),
                ('discount_type', models.CharField(choices=[('percent', 'Percentage'), ('fixed', 'Fixed Amount')], default='percent', max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_uses', models.PositiveIntegerField(default=1)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_codes', to='creator.payableasset')),
            ],
            options={
                'db_table': 'creator_discount_codes',
            },
        ),
        migrations.CreateModel(
            name='CreatorAffiliateProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_percent', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('cookie_days', models.PositiveIntegerField(default=30)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_program', to='creator.payableasset')),
            ],
            options={
                'db_table': 'creator_affiliate_programs',
            },
        ),
        migrations.AddIndex(
            model_name='payableasset',
            index=models.Index(fields=['slug'], name='payable_ass_slug_7e5bc8_idx'),
        ),
        migrations.AddIndex(
            model_name='payableasset',
            index=models.Index(fields=['creator', 'is_active'], name='payable_ass_creator_417d90_idx'),
        ),
        migrations.AddIndex(
            model_name='payableasset',
            index=models.Index(fields=['pricing_type'], name='payable_ass_pricing_870fdb_idx'),
        ),
        migrations.AddIndex(
            model_name='creatorsale',
            index=models.Index(fields=['asset', 'status'], name='creator_sal_asset_i_4c570c_idx'),
        ),
        migrations.AddIndex(
            model_name='creatorsale',
            index=models.Index(fields=['buyer_email'], name='creator_sal_buyer_e_3e2856_idx'),
        ),
        migrations.AddIndex(
            model_name='creatorsale',
            index=models.Index(fields=['created_at'], name='creator_sal_created_45ff7a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='creatordiscountcode',
            unique_together={('asset', 'code')},
        ),
    ]
