# Generated by Django 6.0.6 on 2026-06-09 10:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_name', models.CharField(max_length=120)),
                ('slug', models.SlugField(help_text='URL-safe identifier: cashspace.com/pay/<slug>/', max_length=80, unique=True)),
                ('description', models.TextField(blank=True, help_text='Short description shown on checkout pages')),
                ('logo_url', models.URLField(blank=True, help_text='Optional logo displayed on checkout')),
                ('settlement_blockchain', models.CharField(default='TRX', help_text='Blockchain for settlement payout (BTC, ETH, TRX, BASE, POL)', max_length=10)),
                ('settlement_currency', models.CharField(default='USDT', help_text='Currency for settlement payout (BTC, ETH, USDT, USDC, TRX)', max_length=10)),
                ('settlement_wallet_address', models.CharField(blank=True, help_text='Wallet address to receive merchant payouts. Falls back to user default.', max_length=100)),
                ('commission_rate_override', models.DecimalField(blank=True, decimal_places=4, help_text='Override global commission rate for this merchant (0.0 to 1.0). Null = use global.', max_digits=5, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive merchants cannot accept new payments')),
                ('is_verified', models.BooleanField(default=False, help_text="Admin has verified this merchant's business")),
                ('webhook_url', models.URLField(blank=True, help_text='POST here when a payment for this merchant is FILLED')),
                ('webhook_secret', models.CharField(blank=True, help_text='HMAC secret for signing merchant webhooks', max_length=120)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Merchant',
                'verbose_name_plural': 'Merchants',
                'db_table': 'merchants',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(help_text='URL-safe identifier: /pay/<merchant>/<product>/', max_length=80)),
                ('description', models.TextField(blank=True)),
                ('price_usd', models.DecimalField(blank=True, decimal_places=2, help_text='Fixed price in USD. Null for DONATION type (buyer chooses amount).', max_digits=10, null=True)),
                ('min_price_usd', models.DecimalField(decimal_places=2, default=10, help_text='Minimum accepted payment (enforced for DONATION type).', max_digits=10)),
                ('product_type', models.CharField(choices=[('one_time', 'One-time purchase'), ('subscription', 'Subscription'), ('donation', 'Donation / Pay what you want')], default='one_time', max_length=20)),
                ('collect_telegram', models.BooleanField(default=False, help_text='Ask buyer for their Telegram username at checkout')),
                ('collect_discord', models.BooleanField(default=False, help_text='Ask buyer for their Discord username at checkout')),
                ('collect_phone', models.BooleanField(default=False, help_text='Ask buyer for their phone number at checkout')),
                ('collect_custom_field', models.CharField(blank=True, help_text="Label for a custom text field to collect at checkout (e.g. 'Trading account number')", max_length=80)),
                ('success_redirect_url', models.URLField(blank=True, help_text='Redirect buyer here after successful payment (e.g., thank you page)')),
                ('is_active', models.BooleanField(default=True)),
                ('max_purchases', models.PositiveIntegerField(blank=True, help_text='Cap total number of purchases. Null = unlimited.', null=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='merchants.merchant')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'merchant_products',
                'unique_together': {('merchant', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='PostPaymentAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_type', models.CharField(choices=[('telegram_invite', 'Telegram group invite'), ('discord_role', 'Discord role grant'), ('email_delivery', 'Email delivery'), ('webhook', 'Webhook to merchant')], max_length=30)),
                ('priority', models.PositiveSmallIntegerField(default=0, help_text='Actions execute in ascending priority order')),
                ('is_active', models.BooleanField(default=True)),
                ('config', models.JSONField(default=dict, help_text='Action-specific configuration. See ActionType docstring for keys.')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_payment_actions', to='merchants.product')),
            ],
            options={
                'verbose_name': 'Post-Payment Action',
                'verbose_name_plural': 'Post-Payment Actions',
                'db_table': 'post_payment_actions',
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='CustomerCheckout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(help_text="Buyer's email address", max_length=254)),
                ('full_name', models.CharField(blank=True, max_length=120)),
                ('telegram_username', models.CharField(blank=True, help_text='Telegram @username (without @)', max_length=80)),
                ('discord_username', models.CharField(blank=True, help_text='Discord username#tag or just username', max_length=80)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('custom_field_value', models.CharField(blank=True, help_text="Value for the product's custom_collect_field", max_length=255)),
                ('amount_usd', models.DecimalField(decimal_places=2, help_text='Amount the buyer agreed to pay', max_digits=10)),
                ('status', models.CharField(choices=[('initiated', 'Checkout initiated'), ('payment_created', 'Payment session created'), ('completed', 'Payment completed'), ('abandoned', 'Checkout abandoned'), ('refunded', 'Refunded')], db_index=True, default='initiated', max_length=20)),
                ('automation_triggered', models.BooleanField(default=False, help_text='Whether post-payment automation has fired for this checkout')),
                ('automation_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('automation_error', models.TextField(blank=True, help_text='Error message if automation failed')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Any extra data captured at checkout')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_checkout', to='payments.payment')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_checkouts', to='merchants.product')),
            ],
            options={
                'verbose_name': 'Customer Checkout',
                'verbose_name_plural': 'Customer Checkouts',
                'db_table': 'customer_checkouts',
                'indexes': [models.Index(fields=['product', 'status'], name='customer_ch_product_7872e0_idx'), models.Index(fields=['email'], name='customer_ch_email_192c55_idx'), models.Index(fields=['telegram_username'], name='customer_ch_telegra_c0b1e2_idx')],
            },
        ),
    ]
