# Generated by Django 6.0.6 on 2026-06-10 06:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0001_initial'),
        ('payments', '0002_payment_merchant_alter_payment_commission_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantAPIKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('test_publishable_key', models.CharField(help_text='Safe to expose in frontend. Identifies merchant in test mode.', max_length=80, unique=True)),
                ('test_secret_key_hash', models.CharField(help_text='SHA-256 hex digest of the test secret key.', max_length=64)),
                ('test_secret_key_prefix', models.CharField(help_text='First 20 chars for display (e.g. cs_test_sk_aB3xZ9...)', max_length=24)),
                ('live_publishable_key', models.CharField(help_text='Safe to expose in frontend. Identifies merchant in live mode.', max_length=80, unique=True)),
                ('live_secret_key_hash', models.CharField(help_text='SHA-256 hex digest of the live secret key.', max_length=64)),
                ('live_secret_key_prefix', models.CharField(help_text='First 20 chars for display.', max_length=24)),
                ('is_test_mode', models.BooleanField(db_index=True, default=True, help_text='True = sandbox mode. False = live mode. Toggle from dashboard.')),
                ('test_key_rotated_at', models.DateTimeField(auto_now_add=True, help_text='Last time the test secret key was rotated.')),
                ('live_key_rotated_at', models.DateTimeField(auto_now_add=True, help_text='Last time the live secret key was rotated.')),
            ],
            options={
                'verbose_name': 'Merchant API Keys',
                'verbose_name_plural': 'Merchant API Keys',
                'db_table': 'merchant_api_keys',
            },
        ),
        migrations.CreateModel(
            name='WebhookDeliveryLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('payment.completed', 'Payment completed'), ('payment.failed', 'Payment failed'), ('checkout.initiated', 'Checkout initiated'), ('automation.fired', 'Automation fired'), ('test.webhook', 'Test webhook')], db_index=True, max_length=40)),
                ('is_test', models.BooleanField(db_index=True, default=False, help_text='True if fired in test mode.')),
                ('endpoint_url', models.URLField(help_text='The URL we POSTed to.', max_length=500)),
                ('request_body', models.JSONField(help_text='Exact payload we sent.')),
                ('request_headers', models.JSONField(default=dict, help_text='Headers sent (excluding secrets).')),
                ('response_status_code', models.PositiveIntegerField(blank=True, help_text="HTTP status code returned by merchant's server.", null=True)),
                ('response_body', models.TextField(blank=True, help_text='First 2KB of response body.')),
                ('duration_ms', models.PositiveIntegerField(blank=True, help_text='Round-trip time in milliseconds.', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success (2xx)'), ('failed', 'Failed (non-2xx or timeout)'), ('retrying', 'Retrying'), ('exhausted', 'Max retries exhausted')], db_index=True, default='pending', max_length=12)),
                ('attempt_number', models.PositiveSmallIntegerField(default=1, help_text='Which attempt this is (1 = first, 2 = first retry, etc.)')),
                ('next_retry_at', models.DateTimeField(blank=True, help_text='When the next retry is scheduled.', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Exception or error detail if delivery failed.')),
            ],
            options={
                'verbose_name': 'Webhook Delivery Log',
                'verbose_name_plural': 'Webhook Delivery Logs',
                'db_table': 'webhook_delivery_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='customercheckout',
            name='is_test',
            field=models.BooleanField(db_index=True, default=False, help_text='True if this checkout was created in test mode'),
        ),
        migrations.AlterField(
            model_name='customercheckout',
            name='automation_error',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='customercheckout',
            name='automation_triggered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customercheckout',
            name='custom_field_value',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='customercheckout',
            name='discord_username',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='customercheckout',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='customercheckout',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='webhook_url',
            field=models.URLField(blank=True, help_text='POST here when any payment for this merchant is FILLED'),
        ),
        migrations.AddIndex(
            model_name='customercheckout',
            index=models.Index(fields=['is_test', 'status'], name='customer_ch_is_test_7e1cca_idx'),
        ),
        migrations.AddField(
            model_name='merchantapikey',
            name='merchant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='merchants.merchant'),
        ),
        migrations.AddField(
            model_name='webhookdeliverylog',
            name='checkout',
            field=models.ForeignKey(blank=True, help_text='The checkout that triggered this webhook, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_logs', to='merchants.customercheckout'),
        ),
        migrations.AddField(
            model_name='webhookdeliverylog',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_delivery_logs', to='merchants.merchant'),
        ),
        migrations.AddIndex(
            model_name='webhookdeliverylog',
            index=models.Index(fields=['merchant', 'status'], name='webhook_del_merchan_bd9863_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdeliverylog',
            index=models.Index(fields=['merchant', 'event_type'], name='webhook_del_merchan_493fdc_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdeliverylog',
            index=models.Index(fields=['status', 'next_retry_at'], name='webhook_del_status_26fda1_idx'),
        ),
    ]
